### ISSUE TITLE
Crashes on split view

### ISSUE THREAD

**Issue by shuvashish76** [simenheg/simple-chess-clock#19]
**Steps to produce**
1. Click on setting gear icon
2.  Click on split view (by long click on device recent button from navigation bar)
App crashes

**Crash logs**

```
FATAL EXCEPTION: main
Process: com.chessclock.android, PID: 31876
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.chessclock.android/com.chessclock.android.Prefs}: android.content.res.Resources$NotFoundException: Resource ID #0x7f040000
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2781)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2859)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4702)
	at android.app.ActivityThread.-wrap18(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1598)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6518)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f040000
	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:215)
	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2134)
	at android.content.res.Resources.getXml(Resources.java:1192)
	at android.preference.GenericInflater.inflate(GenericInflater.java:262)
	at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:324)
	at android.preference.PreferenceActivity.addPreferencesFromResource(PreferenceActivity.java:1549)
	at com.chessclock.android.Prefs.onCreate(Prefs.java:62)
	at android.app.Activity.performCreate(Activity.java:7023)
	at android.app.Activity.performCreate(Activity.java:7014)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2734)
	... 10 more
```

**Comment by simenheg** [comment]
Thank you @shuvashish76! However I'm unable to reproduce it; here it simple says "this app can't be used with multiple windows".

Could you provide some more details, such as your Android version and version of the app? Would you be able to help out coding a fix for it?

**Comment by shuvashish76** [comment]
app version: 2.6.1 (21) [F-Droid]
Device: Lenovo Tab4 8 plus (TB-8704X)
Android version: 8.1.0

Sorry I'm not dev, I've 0 knowledge in coding :(

https://user-images.githubusercontent.com/48226312/133895764-17cd7b39-e2dc-4f9c-8ffa-960be7ab71b0.mp4

**Comment by simenheg** [comment]
> app version: 2.6.1 (21) [F-Droid]
> Device: Lenovo Tab4 8 plus (TB-8704X)
> Android version: 8.1.0

Thanks. I'm on the same major version of Android (8.0.0), but can't reproduce it here.
