### ISSUE TITLE
[Feature Request] Support "Device Orientation"

### ISSUE THREAD

**Issue by shuvashish76** [simenheg/simple-chess-clock#20]
**Is your feature request related to a problem? Please describe.**
I'm using this app on my android Tablet & most of the times I use landscape mode by default for all apps.

**Steps to reproduce the behavior:**

1.Turn on device "Auto-rotate"
2. Go to SCC (Simple Chess Clock) app & rotate your device to landscape / reverse-landscape / reverse-portrait mode
3. App remains in Portrait mode

**Describe the solution you'd like**
App should support device "Auto-rotation" feature.

**Describe alternatives you've considered**
There are other apps which can force any app to device rotation for ex: [Tap 'n' Turn](https://github.com/gabm/TapAndTurn).
But in my opinion it would be nice if the app itself support device rotation than being forced by another app.

**Comment by shuvashish76** [comment]
Currently how it looks with landscape mode (forced by Tap 'n' Turn app)👇🏿
![Screenshot_2021-09-18-23-14-11](https://user-images.githubusercontent.com/48226312/133897821-a4283cd4-a662-453e-9f8f-a2cb43e8731e.jpeg)

But clicking the setting icon crashes the app. (related #19)

**Crash logs**

```
FATAL EXCEPTION: main
Process: com.chessclock.android, PID: 11208
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.chessclock.android/com.chessclock.android.Prefs}: android.content.res.Resources$NotFoundException: Resource ID #0x7f040000
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2781)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2859)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1592)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6518)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f040000
	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:215)
	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2134)
	at android.content.res.Resources.getXml(Resources.java:1192)
	at android.preference.GenericInflater.inflate(GenericInflater.java:262)
	at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:324)
	at android.preference.PreferenceActivity.addPreferencesFromResource(PreferenceActivity.java:1549)
	at com.chessclock.android.Prefs.onCreate(Prefs.java:62)
	at android.app.Activity.performCreate(Activity.java:7023)
	at android.app.Activity.performCreate(Activity.java:7014)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2734)
	... 9 more
```

**Comment by simenheg** [comment]
Hi again @shuvashish76, thanks for your suggestion. This would be a nice feature to have I think.

**Comment by laksh-21** [comment]
Hi @simenheg can I work on this? :)

**Comment by simenheg** [comment]
That would be great @laksh-21, thanks!
